# Sequences 

In [27]:
s = "ceci est un test"
print(s[0], s[0:3])
print(s[::2])
print(s[::-1])

c cec
cc s nts
tset nu tse icec


## Slices with list 

In [28]:
my_list = [0, 2, 4, 8, 16, 32, 64, 128]
my_list

[0, 2, 4, 8, 16, 32, 64, 128]

In [29]:
my_list[::-1]

[128, 64, 32, 16, 8, 4, 2, 0]

In [30]:
my_list[2:4] = [100, 200, 300, 400, 500]
my_list

[0, 2, 100, 200, 300, 400, 500, 16, 32, 64, 128]

In [34]:
my_list*2

[0,
 2,
 100,
 200,
 300,
 400,
 500,
 16,
 32,
 64,
 128,
 0,
 2,
 100,
 200,
 300,
 400,
 500,
 16,
 32,
 64,
 128]

## Numpy introduction

## matrix calculus

In [31]:
import numpy as np

In [32]:
my_array = np.array([1, 2, 3, 4 , 5])
my_array

array([1, 2, 3, 4, 5])

In [33]:
10*my_array

array([10, 20, 30, 40, 50])

In [38]:
my_array[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [40]:
new_array = my_array[:, np.newaxis] + 100*my_array
new_array

array([[101, 201, 301, 401, 501],
       [102, 202, 302, 402, 502],
       [103, 203, 303, 403, 503],
       [104, 204, 304, 404, 504],
       [105, 205, 305, 405, 505]])

In [41]:
centre = new_array[1:4,1:4]
centre

array([[202, 302, 402],
       [203, 303, 403],
       [204, 304, 404]])

## number of elements

built-in function **len**

In [2]:
len(s)

16

In [3]:
s[15]

't'

## Operators

min and max

In [17]:
print(f"min:{min(s)};max:{max(s)}")

min: ;max:u


## operator belong to 

In [4]:
"un" in s

True

In [5]:
"un" not in s

False

## Concatenation 

In [24]:
s + ";autre test"

'ceci est un test;autre test'

## Count number of occurences  

In [6]:
s.count("un")

1

In [7]:
s.count("t")

3

In [8]:
s.index("t")

7

## Slicing


In [19]:
s[3:20:2]

'ietu et'

In [10]:
s[3:20:-1]

''

In [21]:
s[20:3:-1]

'tset nu tse '

In [11]:
s[-10:-3]

'st un t'

In [12]:
s[-10:-3:-1]

''

In [22]:
s[-3:-10:-1]

'et nu t'

In [20]:
s[::-1]

'tset nu tse icec'